### PR TITLE
Grammatical typo fix

### PR DESCRIPTION
**Pull request by JustinPihony**
This is a simple documentation fix for a change from "does currently not" to "currently does not"

### CODE REVIEW

**Review by raboof — COMMENTED** [review]
Hi @JustinPihony - thanks for the updates! Unfortunately this repo is not the 'source' for these texts: it's a backup of the generated documentation published to doc.akka.io .

The Akka HTTP change can be made 'upstream' at https://github.com/akka/akka-http/blob/master/docs/src/main/paradox/security/2021-02-24-incorrect-handling-of-Transfer-Encoding-header.md .

The other changes are for Akka 1.x, so I don't think it's useful to fix them retro-actively.

**Comment by raboof** [comment]
(I added a README.md to this repo to make this somewhat more clear)

**Comment by raboof** [comment]
Oh, I see you already found that (https://github.com/akka/akka-http/pull/3788) :+1: .

**Comment by JustinPihony** [comment]
I guess I was trying to fix it everywhere, but in hindsight - unless you are going to re-push it out then this would unsync things. Closing :)

**Pull request closed without merging**
